<a href="https://colab.research.google.com/github/BlueBerry-Coder/TestWork/blob/main/Task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [4]:
# Import Data
spam_df = pd.read_csv('/content/test.csv')
spam_df

label                                              email
0      ham                  Why you keeping me away like this
1      ham   neale pickett if you can spare the memory you...
2      ham                   I think u have the wrong number.
3      ham  * Was thinking about chuckin ur red green n bl...
4      ham  i am trying to manage the email for a domain w...
...    ...                                                ...
2884   ham            Did he just say somebody is named tampa
2885   ham  Nationwide auto centre (or something like that...
2886   ham                 Sorry, I'll call later In meeting.
2887   ham  Yun buying... But school got offer 2000 plus o...
2888   ham  Yes i think so. I am in office but my lap is i...

[2889 rows x 2 columns]

In [7]:
# Inspect Data
spam_df.groupby('label').describe()

email                                                               
      count unique                                                top freq
label                                                                     
ham    2467   2413                             Sorry, I'll call later   11
spam    422    397  Please call our customer service representativ...    4

In [9]:
# Conversion: spam-->1, ham-->0
spam_df['spam'] = spam_df['label'].apply(lambda x: 1 if x == 'spam' else 0)
spam_df

label                                              email  spam
0      ham                  Why you keeping me away like this     0
1      ham   neale pickett if you can spare the memory you...     0
2      ham                   I think u have the wrong number.     0
3      ham  * Was thinking about chuckin ur red green n bl...     0
4      ham  i am trying to manage the email for a domain w...     0
...    ...                                                ...   ...
2884   ham            Did he just say somebody is named tampa     0
2885   ham  Nationwide auto centre (or something like that...     0
2886   ham                 Sorry, I'll call later In meeting.     0
2887   ham  Yun buying... But school got offer 2000 plus o...     0
2888   ham  Yes i think so. I am in office but my lap is i...     0

[2889 rows x 3 columns]

from matplotlib import pyplot as plt
spam_df['spam'].plot(kind='hist', bins=20, title='spam')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
spam_df.groupby('label').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
spam_df['spam'].plot(kind='line', figsize=(8, 4), title='spam')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(spam_df['label'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(spam_df, x='spam', y='label', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

from matplotlib import pyplot as plt
_df_0['index'].plot(kind='hist', bins=20, title='index')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['spam'].plot(kind='hist', bins=20, title='spam')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_2.groupby('label').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3.plot(kind='scatter', x='index', y='spam', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  xs = series['index']
  ys = series['spam']
  
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_4.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('label')):
  _plot_series(series, series_name, i)
  fig.legend(title='label', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('spam')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_5.sort_values('index', ascending=True)
for i, (series_name, series) in enumerate(df_sorted.groupby('label')):
  _plot_series(series, series_name, i)
  fig.legend(title='label', bbox_to_anchor=(1, 1), loc='upper left')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_6['index'].plot(kind='line', figsize=(8, 4), title='index')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_7['spam'].plot(kind='line', figsize=(8, 4), title='spam')
plt.gca().spines[['top', 'right']].set_visible(False)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_8['label'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_8, x='index', y='label', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

<string>:5: FutureWarning: 

Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `y` variable to `hue` and set `legend=False` for the same effect.



from matplotlib import pyplot as plt
import seaborn as sns
figsize = (12, 1.2 * len(_df_9['label'].unique()))
plt.figure(figsize=figsize)
sns.violinplot(_df_9, x='spam', y='label', inner='box', palette='Dark2')
sns.despine(top=True, right=True, bottom=True, left=True)

In [11]:
x_train, x_test, y_train, y_test = train_test_split(spam_df.email, spam_df.spam)

In [12]:
x_train.describe()

count                       2166
unique                      2115
top       Sorry, I'll call later
freq                           9
Name: email, dtype: object

In [16]:
# Counting and collecting Data into a matrix
cv = CountVectorizer()
x_train_count = cv.fit_transform(x_train.values)

In [17]:
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [18]:
# Train model
model = MultinomialNB()
model.fit(x_train_count, y_train)

MultinomialNB()

In [19]:
# Check Ham
email_ham = ['I think u have the wrong number.']
email_ham_count = cv.transform(email_ham)
model.predict(email_ham_count)

array([0])

In [21]:
# Check Spam
email_spam = ['Double your mins & txts on Orange or 1/2 price linerental - Motorola and SonyEricsson with B/Tooth FREE-Nokia FREE Call MobileUpd8 on 08000839402 or2optout/HV9D']
email_spam_count = cv.transform(email_spam)
model.predict(email_spam_count)

array([1])

In [22]:
# Test model
x_test_count = cv.transform(x_test)
model.score(x_test_count, y_test)

0.9488243430152143